export const movies=[
    { id:1,title:"The Avanger!",
      plot:"Supernatural power shown in the movie !",
      price: 199,
      poster:"https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SL1500_.jpg",
      rating:8.9,
       fav:false,
      stars:0,
      inCart:false,
     },{ id:2,title:"The Avanger!",
      plot:"Supernatural power shown in the movie !",
      price: 199,
      poster:"https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SL1500_.jpg",
      rating:8,
       fav:false,
      stars:0,
      inCart:false,
     },{ id:3,title:"The Avanger!",
      plot:"Supernatural power shown in the movie !",
      price: 199,
      poster:"https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SL1500_.jpg",
      rating:7,
       fav:false,
      stars:0,
      inCart:false,
     }
]